apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: camp-deployment
spec:
  selector:
    matchLabels:
      app: camp
  replicas: 1 
  template:
    metadata:
      labels:
        app: camp
    spec:
      containers:
      - name: camp
        #image: 401110809112.dkr.ecr.eu-central-1.amazonaws.com/camp/application-service:latest
        #image: registry.hub.docker.com/rebaze/camp-application-service:latest
        #image: quay.io/rebaze/camp-dev
        image: eu.gcr.io/golemite/application-service
        imagePullPolicy: "Always"
        #imagePullSecrets:
        #        #  - name: tonit-pull-secret
        ports:
          - containerPort: 8080
